"""
Commercial Telegram Formatter
Separate message formats for FREE and VIP channels
"""
import re

def escape_md(text: str) -> str:
    """Escape special characters for Telegram Markdown v2"""
    return re.sub(r'([_*\[\]()~`>#+\-=|{}.!])', r'\\\1', str(text))


def format_free_message(payload: dict) -> str:
    """
    Format signal for FREE channel (Marketing-focused).
    
    Features:
    - Simplified information
    - No TP/SL details
    - Delayed signal notice
    - VIP upgrade CTA
    
    Args:
        payload: Signal data
        
    Returns:
        str: Formatted FREE message
    """
    asset = payload.get("symbol") or payload.get("asset", "EUR/USD")
    direction = payload.get("direction", "BUY")
    entry = payload.get("entry", 0)
    confidence = payload.get("confidence", 0)
    
    # Handle entry as array or single value
    if isinstance(entry, list):
        entry_text = f"{entry[0]}"
    else:
        entry_text = str(entry)
    
    dir_emoji = "🟢" if direction == "BUY" else "🔴"
    
    return f"""🔥 *HIGH CONFIDENCE SIGNAL*

📊 *{escape_md(asset)}*
{dir_emoji} Action: {direction}
🎯 Entry: {entry_text}
⭐ Confidence: {confidence}%

⏳ _Delayed Signal_
📈 _For educational purposes only_

👉 Join VIP for real\\-time \\& full analysis

⚠️ _This signal is generated by an AI\\-assisted system\\._
_Not financial advice\\. Trade at your own risk\\._""".strip()


def format_vip_message(payload: dict) -> str:
    """
    Format signal for VIP channel (Trader-grade).
    
    Features:
    - Full trading details
    - TP/SL levels
    - Strategy explanation
    - Risk assessment
    - Professional disclaimer
    
    Args:
        payload: Signal data
        
    Returns:
        str: Formatted VIP message
    """
    asset = payload.get("symbol") or payload.get("asset", "EUR/USD")
    direction = payload.get("direction", "BUY")
    entry = payload.get("entry", 0)
    tp = payload.get("tp", 0)
    sl = payload.get("sl", 0)
    confidence = payload.get("confidence", 0)
    timeframe = payload.get("timeframe", "M15")
    strategy = payload.get("strategy", "Rule Engine")
    
    # Handle entry as array or single value
    if isinstance(entry, list):
        entry_text = f"{entry[0]} – {entry[1]}"
    else:
        entry_text = str(entry)
    
    # Risk assessment
    if confidence >= 90:
        risk = "Low"
    elif confidence >= 80:
        risk = "Medium"
    else:
        risk = "Medium\\-High"
    
    dir_emoji = "🟢" if direction == "BUY" else "🔴"
    
    return f"""🚨 *TRADE SIGNAL – HIGH CONFIDENCE*

📊 *{escape_md(asset)}*
{dir_emoji} Action: {direction}
🎯 Entry: {entry_text}
🎯 TP: {tp}
🛑 SL: {sl}

⭐ Confidence: {confidence}% \\(HIGH\\)
🧠 Strategy: {escape_md(strategy)}
⏰ Timeframe: {timeframe}

⚠️ Risk: {risk}
📌 Manage position size carefully

⚠️ _This signal is generated by an AI\\-assisted system\\._
_Not financial advice\\. Trade at your own risk\\._""".strip()


def format_message_by_tier(payload: dict, channel_type: str = "vip") -> str:
    """
    Route to appropriate formatter based on channel type.
    
    Args:
        payload: Signal data
        channel_type: "free" or "vip"
        
    Returns:
        str: Formatted message
    """
    if channel_type.lower() == "free":
        return format_free_message(payload)
    else:
        return format_vip_message(payload)
